<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JoinMemberBegin</name>
   <tag></tag>
   <elementGuidId>89378081-b8a7-4236-af61-2bc141c79bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div[2]/div[1]/div/div[2]/form/div[2]/div/div/input[1][count(. | //input[@type = 'number' and @ng-model = 'self.balanceBegin']) = count(//input[@type = 'number' and @ng-model = 'self.balanceBegin'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[2]/div[1]/div/div[2]/form/div[2]/div/div/input[1]</value>
   </webElementProperties>
</WebElementEntity>
