<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_AnyTimeDiscountValue</name>
   <tag></tag>
   <elementGuidId>68f78976-a4a0-40a7-a2cf-2a3db29625b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;result&quot;]/div/div[2]/div/table/tbody/tr/td[7]</value>
   </webElementProperties>
</WebElementEntity>
