<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>存款次數</description>
   <name>txt_ActualDepositCount</name>
   <tag></tag>
   <elementGuidId>9d9533a5-abc7-43dc-989f-10e89b0500f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(9)>div>div>a:nth-child(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
