<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Operator</name>
   <tag></tag>
   <elementGuidId>c187bfb7-55e2-4d24-9c70-f87dfeb87901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[7]/div/input[count(. | //input[@type = 'text' and @ng-model = 'self.query.Name']) = count(//input[@type = 'text' and @ng-model = 'self.query.Name'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[7]/div/input</value>
   </webElementProperties>
</WebElementEntity>
