<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BankPayee</name>
   <tag></tag>
   <elementGuidId>fe69bb86-633a-4714-80b3-2092a9a2ba7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[9]/div/input[count(. | //input[@type = 'text' and @ng-model = 'self.query.GroupAccountPersonName' and @placeholder = '可输入多个，请以半形逗号隔开']) = count(//input[@type = 'text' and @ng-model = 'self.query.GroupAccountPersonName' and @placeholder = '可输入多个，请以半形逗号隔开'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[9]/div/input</value>
   </webElementProperties>
</WebElementEntity>
