<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>存款金额</description>
   <name>input_DepositAmount</name>
   <tag></tag>
   <elementGuidId>cf8b9d27-1d68-4ebb-a7e8-a27e7c8090ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amount</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
