<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_DetailAccount</name>
   <tag></tag>
   <elementGuidId>1bd1f000-9d50-4ee8-8b54-eba8caf2c6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/root-component/div/div/div[1]/h2/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/root-component/div/div/div[1]/h2/small</value>
   </webElementProperties>
</WebElementEntity>
