<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>CQ9的局號</description>
   <name>txt_CQ9FishGameID</name>
   <tag></tag>
   <elementGuidId>60858f96-d343-40ad-aee2-95f72175d333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rawDataTable&quot;]/tbody/tr[2]/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rawDataTable&quot;]/tbody/tr[2]/td/div</value>
   </webElementProperties>
</WebElementEntity>
