<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ApplicationDateBegin</name>
   <tag></tag>
   <elementGuidId>2d2cdc3e-a7e1-4a14-ba01-b5b933095dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[4]/div/div/input[1][count(. | //input[@type = 'text' and @ng-model = 'self.query.ApplyDateBegin']) = count(//input[@type = 'text' and @ng-model = 'self.query.ApplyDateBegin'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[4]/div/div/input[1]</value>
   </webElementProperties>
</WebElementEntity>
