<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccountName</name>
   <tag></tag>
   <elementGuidId>d5d044dc-64db-4a27-b439-cb0018bd8ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
