<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>佣金计算</description>
   <name>link_CommissionCalculation</name>
   <tag></tag>
   <elementGuidId>5c5b6f88-bb6c-44c7-8041-8630b56fb0fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(8)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
