<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>优惠汇入</description>
   <name>link_PromotionImport</name>
   <tag></tag>
   <elementGuidId>fe94b8d2-17ef-444b-8dcc-c3aefbf8106e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(10)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
