<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>取款申请审核</description>
   <name>link_VerifyWithdrawalApplication</name>
   <tag></tag>
   <elementGuidId>6efdf3f8-b30d-4b81-a6c0-c13fc77f1424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(5)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
