<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>转帐额度确认</description>
   <name>link_TransferAmountConfirmatiom</name>
   <tag></tag>
   <elementGuidId>3012b299-3b1e-4c4c-8ba8-a6fbf049e38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(9)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
