<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>公司入款审核</description>
   <name>link_VerifyBankDesposit</name>
   <tag></tag>
   <elementGuidId>d86604a1-98e0-420d-b081-9bbb0f6cdfb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(3)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
