<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>线上支付看板</description>
   <name>link_OnlinePaymentList</name>
   <tag></tag>
   <elementGuidId>62bbaee6-c883-4dbc-97ef-25d7b98b2f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2)>ul>li:nth-child(4)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
