<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>会员与代理商</description>
   <name>link_MemberAndAgentMenu</name>
   <tag></tag>
   <elementGuidId>60db51f0-efde-4c87-bc47-402cc23124f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-child(1)>li:nth-child(1)>a>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>ul:nth-child(1)>li:nth-child(1)>a>span</value>
   </webElementProperties>
</WebElementEntity>
