<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Top</name>
   <tag></tag>
   <elementGuidId>114a436e-7fa2-40cf-91d3-6878d1ca12cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/root-component/menu-component/nav/div/div[2]/ul[1]/li[${top_num}]/a/span</value>
   </webElementProperties>
</WebElementEntity>
