<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_RepotrsList</name>
   <tag></tag>
   <elementGuidId>da2b2353-97f7-4420-8e01-c9f90048fbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/root-component/menu-component/nav/div/div[2]/ul[1]/li[4]/ul/li[${list_num}]/a</value>
   </webElementProperties>
</WebElementEntity>
