<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>投注记录查询</description>
   <name>link_SearchForBettingRecords</name>
   <tag></tag>
   <elementGuidId>dd174fec-6482-4d58-a7bc-c3f03b773c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(4)>ul>li:nth-child(4)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
