<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>历史投注记录查询</description>
   <name>link_SearchForHistoricalBettingRecords</name>
   <tag></tag>
   <elementGuidId>6b195d29-d29e-4969-875a-e83749f6b365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(4)>ul>li:nth-child(5)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
