<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>遊戲類型，選取的按鈕</description>
   <name>button_Category</name>
   <tag></tag>
   <elementGuidId>f3518465-8b72-43e1-98fd-b3239d7267d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btn-category&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
