<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>投注時間</description>
   <name>input_WagersTimeBegin</name>
   <tag></tag>
   <elementGuidId>cc602cfc-9171-4807-a40e-e645b6ce80a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wagersTimeBegin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
