<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>公司入款帐户管理</description>
   <name>link_BankDepositAccountManagment</name>
   <tag></tag>
   <elementGuidId>9ba6d34e-9416-457a-92e9-0a23235e81dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(4)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
