<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>优惠管理</description>
   <name>link_PromotionManagment</name>
   <tag></tag>
   <elementGuidId>403b9ae4-a4c9-41a1-9ef3-2faac2dbbf93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(11)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
