<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>站內信</description>
   <name>link_InternalMail</name>
   <tag></tag>
   <elementGuidId>dc5a8394-4157-45f2-ad99-85040fe566d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(10)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
