<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>站台系统值设置</description>
   <name>link_WebsiteSystemConfigure</name>
   <tag></tag>
   <elementGuidId>fc89aa2c-9dc4-4362-ba1b-bd746d2bcc1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(13)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
