<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>活动管理</description>
   <name>link_EventSetting</name>
   <tag></tag>
   <elementGuidId>18876588-5d58-4a96-978a-a61ff65627d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(15)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
