<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>线上支付商户管理</description>
   <name>link_OnlinePaymentAccountManagment</name>
   <tag></tag>
   <elementGuidId>ce804cc1-ee8c-418b-a7e8-2d43ec759dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(3)>ul>li:nth-child(5)>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
