<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OnlineWithdrawal</name>
   <tag></tag>
   <elementGuidId>f2ee12e6-0fc1-4113-971e-c15453fb9fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div:nth-child(8)>div>label:nth-child(3)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-child(8)>div>label:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>div:nth-child(8)>div>label:nth-child(3)</value>
   </webElementProperties>
</WebElementEntity>
