<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>3a6be8f8-8c4b-416c-a74c-b491640dbbaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[9]/div/button[2][count(. | //button[@type = 'button' and (text() = '取消' or . = '取消')]) = count(//button[@type = 'button' and (text() = '取消' or . = '取消')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[9]/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
