<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AmountEnd</name>
   <tag></tag>
   <elementGuidId>4aa21621-5581-4c5e-a94f-c9ca21bb1cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[5]/div/div/input[2][count(. | //input[@type = 'number']) = count(//input[@type = 'number'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchModal&quot;]/div/div/div[2]/form/div[5]/div/div/input[2]</value>
   </webElementProperties>
</WebElementEntity>
